import { withNormalLayout } from "src/HOCs";
import { NotFound } from "./pages/NotFound";
import { AllBeneficiaries } from "./pages/BeneficiariesAll";
import { ShowBeneficiary } from "./pages/Beneficiary";
import { ShowBeneficiaryRequests } from "./pages/BeneficiaryRequests";
import { AddRequest } from "./pages/RequestAdd";
import { Groups } from "./pages/Groups";
import { GroupShow } from "./pages/GroupShow";
import { Plans } from "./pages/Plans";
import { PlanShow } from "./pages/PlanShow";

export const NotFoundPage = withNormalLayout(NotFound);
export const AllBeneficiariesPage = withNormalLayout(AllBeneficiaries);
export const ShowBeneficiaryPage = withNormalLayout(ShowBeneficiary);
export const ShowBeneficiaryRequestsPage = withNormalLayout(ShowBeneficiaryRequests);
export const AddRequestPage = withNormalLayout(AddRequest);
export const GroupsPage = withNormalLayout(Groups);
export const GroupShowPage = withNormalLayout(GroupShow);
export const PlansPage = withNormalLayout(Plans);
export const PlanShowPage = withNormalLayout(PlanShow);
