import { withNormalLayout } from "src/HOCs";
import { Buttons } from "./pages/Buttons";
import { Cards } from "./pages/Cards";
import { Inputs } from "./pages/Inputs";
import { Switches } from "./pages/Switches";
import { Radios } from "./pages/Radios";
import { Checkboxes } from "./pages/Checkboxes";
import { Alerts } from "./pages/Alerts";
import { Progresses } from "./pages/Progresses";
import { NotFound } from "./pages/NotFound";
import { Table } from "./pages/Table";
import { Charts } from "./pages/Charts";
import { Snackbars } from "./pages/Snackbars";
import { Home } from "./pages/Home";

export const ButtonsPage = withNormalLayout(Buttons);
export const CardsPage = withNormalLayout(Cards);
export const InputsPage = withNormalLayout(Inputs);
export const SwitchesPage = withNormalLayout(Switches);
export const RadiosPage = withNormalLayout(Radios);
export const CheckboxesPage = withNormalLayout(Checkboxes);
export const AlertsPage = withNormalLayout(Alerts);
export const ProgressesPage = withNormalLayout(Progresses);
export const NotFoundPage = withNormalLayout(NotFound);
export const TablePage = withNormalLayout(Table);
export const ChartsPage = withNormalLayout(Charts);
export const SnackbarsPage = withNormalLayout(Snackbars);
export const HomePage = withNormalLayout(Home);
