import { withNormalLayout } from "src/HOCs";
import { NotFound } from "./pages/NotFound";
import { AllBeneficiaries } from "./pages/BeneficiariesAll";
import { ShowBeneficiary } from "./pages/Beneficiary";
import { ShowBeneficiaryRequests } from "./pages/BeneficiaryRequests";
import { AddRequest } from "./pages/RequestAdd";
import { Groups } from "./pages/Groups";
import { GroupShow } from "./pages/GroupShow";
import { Plans } from "./pages/Plans";
import { PlanShow } from "./pages/PlanShow";
import { Meets } from "./pages/Meets";
import { Doctors } from "./pages/Doctors";
import { DoctorsShow } from "./pages/DoctorsShow";
import { Secretary } from "./pages/Secretary";
import { SecretaryShow } from "./pages/SecretaryShow";

export const NotFoundPage = withNormalLayout(NotFound);
export const AllBeneficiariesPage = withNormalLayout(AllBeneficiaries);
export const ShowBeneficiaryPage = withNormalLayout(ShowBeneficiary);
export const ShowBeneficiaryRequestsPage = withNormalLayout(ShowBeneficiaryRequests);
export const AddRequestPage = withNormalLayout(AddRequest);
export const GroupsPage = withNormalLayout(Groups);
export const GroupShowPage = withNormalLayout(GroupShow);
export const PlansPage = withNormalLayout(Plans);
export const PlanShowPage = withNormalLayout(PlanShow);
export const MeetsPage = withNormalLayout(Meets);
export const DoctorsPage = withNormalLayout(Doctors);
export const DoctorsShowPage = withNormalLayout(DoctorsShow);
export const SecretaryPage = withNormalLayout(Secretary);
export const SecretaryShowPage = withNormalLayout(SecretaryShow);
